# -*- coding: utf-8 -*-
"""ATSR_FInal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Dn7Ro3w4jx8FRrzzCjb2aHLfcLyhyYK
"""

!pip install -q transformers datasets accelerate bitsandbytes matplotlib seaborn torch
!pip install -q huggingface_hub
print('All packages installed.')

from huggingface_hub import login
login(token="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")

import torch
import warnings
warnings.filterwarnings('ignore')

# ── Experiment config ──────────────────────────────────────────
SAMPLE_SIZE   = 50       # Start with 50. Increase to 200 for real results.
RANDOM_SEED   = 42
MAX_NEW_TOKENS = 150     # Keep short for speed on T4
DEVICE        = 'cuda' if torch.cuda.is_available() else 'cpu'

# ATSR detection thresholds (from paper Appendix B.3)
THRESHOLD_HIDDEN    = -4.5
THRESHOLD_ATTENTION = -5.0
THRESHOLD_ENTROPY   =  2.5

# Detection layers — middle-to-late layers (paper uses 15, 20, 25)
# For 3B model which has 28 layers, we use 10, 18, 24
# Will be set per model below
DETECTION_LAYERS_3B  = [10, 18, 24]
DETECTION_LAYERS_7B  = [15, 20, 25]
DETECTION_LAYERS_8B  = [15, 20, 25]

print(f'Device: {DEVICE}')
print(f'Sample size: {SAMPLE_SIZE}')
if DEVICE == 'cuda':
    print(f'GPU: {torch.cuda.get_device_name(0)}')
    print(f'VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')

from datasets import load_dataset
import random

print('Loading PubMedQA...')
# pubmed_qa has a 'pqa_labeled' split with 1000 expert-labeled instances
dataset = load_dataset('qiaojin/PubMedQA', 'pqa_labeled', split='train')

# Sample consistently
random.seed(RANDOM_SEED)
indices = random.sample(range(len(dataset)), SAMPLE_SIZE)
samples = dataset.select(indices)

print(f'Loaded {len(samples)} samples from PubMedQA')
print('\nExample:')
print(f'  Q: {samples[0]["question"][:100]}...')
print(f'  A: {samples[0]["long_answer"][:100]}...')
print(f'  Label: {samples[0]["final_decision"]}')

import re
from collections import Counter

def normalize_text(text):
    """Lowercase, remove punctuation, collapse whitespace."""
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def compute_f1(prediction, ground_truth):
    """
    Token-level F1 between prediction and ground truth.
    Standard SQuAD-style metric.
    """
    pred_tokens  = normalize_text(prediction).split()
    truth_tokens = normalize_text(ground_truth).split()

    if not pred_tokens or not truth_tokens:
        return 0.0

    pred_counter  = Counter(pred_tokens)
    truth_counter = Counter(truth_tokens)

    # Overlap
    overlap = sum((pred_counter & truth_counter).values())

    if overlap == 0:
        return 0.0

    precision = overlap / len(pred_tokens)
    recall    = overlap / len(truth_tokens)
    f1        = 2 * precision * recall / (precision + recall)
    return f1

# Quick sanity check
test_f1 = compute_f1("the patient has hypertension", "the patient has hypertension and diabetes")
print(f'F1 sanity check (partial overlap): {test_f1:.3f}')  # Should be ~0.75

import torch
import numpy as np

# ── Stage 2: Three Detection Scores ───────────────────────────

def compute_hidden_score(outputs, detection_layers):
    """
    Hidden Score = (2/m) * sum(log(sigma_i))
    where sigma_i are singular values of hidden state matrix H (d x m).
    Higher = more spread = hallucination signal.
    """
    scores = []
    hidden_states = outputs.hidden_states  # tuple of (1, seq_len, hidden_dim)

    for layer_idx in detection_layers:
        if layer_idx >= len(hidden_states):
            continue
        H = hidden_states[layer_idx][0].float()  # (seq_len, hidden_dim)
        H = H.T  # (hidden_dim, seq_len) = (d, m)
        m = H.shape[1]

        try:
            _, sigma, _ = torch.linalg.svd(H, full_matrices=False)
            score = (2.0 / m) * torch.sum(torch.log(sigma + 1e-8)).item()
            scores.append(score)
        except Exception:
            pass

    return float(np.mean(scores)) if scores else 0.0


def compute_attention_score(outputs, detection_layers):
    # Fallback if attentions unavailable
    if outputs.attentions is None:
        return 0.0

    scores = []
    attentions = outputs.attentions

    for layer_idx in detection_layers:
        if layer_idx >= len(attentions):
            continue
        attn = attentions[layer_idx][0].float()

        for head in range(attn.shape[0]):
            kernel = attn[head]
            diag   = torch.diagonal(kernel)
            score  = torch.mean(torch.log(diag + 1e-8)).item()
            scores.append(score)

    return float(np.mean(scores)) if scores else 0.0


def compute_logit_entropy(outputs, window_size=10, top_k=50):
    """
    Logit Entropy = max windowed entropy over top-k softmax probabilities.
    High entropy = uncertain token choice = likely hallucination.
    """
    logits = outputs.logits[0].float()  # (seq_len, vocab_size)

    # Top-k probs at each position, renormalized
    top_vals = torch.softmax(logits, dim=-1).topk(top_k, dim=-1).values
    top_vals = top_vals / (top_vals.sum(dim=-1, keepdim=True) + 1e-8)

    # Per-token entropy
    entropy = -torch.sum(top_vals * torch.log(top_vals + 1e-8), dim=-1)  # (seq_len,)

    # Windowed max
    seq_len = entropy.shape[0]
    if seq_len < window_size:
        return entropy.mean().item()

    max_window = 0.0
    for i in range(seq_len - window_size):
        val = entropy[i:i + window_size].mean().item()
        if val > max_window:
            max_window = val

    return max_window


def teacher_forcing_pass(question, answer, model, tokenizer):
    text   = f"Question: {question}\nAnswer: {answer}"
    inputs = tokenizer(
        text,
        return_tensors='pt',
        truncation=True,
        max_length=512
    ).to(model.device)

    with torch.no_grad():
        outputs = model(
            **inputs,
            output_hidden_states=True,
            output_attentions=True
        )

    if outputs.attentions is None:
        raise RuntimeError("outputs.attentions is None")

    return outputs, inputs


def is_hallucinated(h_score, a_score, e_score):
    """Trigger decision: any signal above threshold → hallucination detected."""
    return (
        h_score > THRESHOLD_HIDDEN or
        a_score > THRESHOLD_ATTENTION or
        e_score > THRESHOLD_ENTROPY
    )


# ── Stage 3: Token Localization ────────────────────────────────

def localize_hallucinated_tokens(outputs, tokenizer, inputs, top_n=5):
    """
    Rank tokens by attention diagonal score.
    Return top-n most suspicious token strings.
    """
    mid_layer = len(outputs.attentions) // 2
    attn      = outputs.attentions[mid_layer][0].float()  # (heads, seq, seq)

    # Average diagonal across heads
    diag_scores = torch.stack([
        torch.diagonal(attn[h]) for h in range(attn.shape[0])
    ]).mean(dim=0)  # (seq_len,)

    actual_top_n = min(top_n, diag_scores.shape[0])
    top_indices  = diag_scores.topk(actual_top_n).indices
    token_ids    = inputs['input_ids'][0][top_indices]
    tokens       = tokenizer.convert_ids_to_tokens(token_ids)

    # Clean subword markers
    tokens = [t.replace('▁', '').replace('Ġ', '').strip() for t in tokens if t]
    tokens = [t for t in tokens if len(t) > 2]  # filter short tokens

    return tokens[:top_n]


print('ATSR core functions defined.')

def generate_text(prompt, model, tokenizer, max_new_tokens=MAX_NEW_TOKENS):
    """Basic greedy generation helper."""
    inputs = tokenizer(
        prompt,
        return_tensors='pt',
        truncation=True,
        max_length=512
    ).to(model.device)

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,          # greedy for reproducibility
            temperature=1.0,
            pad_token_id=tokenizer.eos_token_id
        )

    # Decode only newly generated tokens
    new_ids = output_ids[0][inputs['input_ids'].shape[1]:]
    return tokenizer.decode(new_ids, skip_special_tokens=True).strip()


def loop1_knowledge(question, flagged_tokens, model, tokenizer, max_iter=2):
    """
    Loop 1: Generate and verify factual background knowledge.
    Flagged tokens explicitly highlighted in prompt.
    """
    flag_str = ', '.join(flagged_tokens) if flagged_tokens else 'all claims'

    for _ in range(max_iter):
        prompt = (
            f"You are a medical expert. Provide accurate factual background about: {question}\n"
            f"Pay special attention to verifying: {flag_str}\n"
            f"Be concise and factually precise. Knowledge:"
        )
        knowledge = generate_text(prompt, model, tokenizer, max_new_tokens=100)

        # Simple factuality check: does it contain hedging language?
        # A very basic proxy — production would use log-prob of rating tokens
        if len(knowledge.split()) > 10:  # has enough content
            break

    return knowledge


def loop2_answer(question, knowledge, flagged_tokens, model, tokenizer, max_iter=2):
    """
    Loop 2: Generate knowledge-consistent corrected answer.
    """
    flag_str = ', '.join(flagged_tokens) if flagged_tokens else 'all claims'

    for _ in range(max_iter):
        prompt = (
            f"Answer this medical question using ONLY the provided knowledge.\n"
            f"Question: {question}\n"
            f"Verified Knowledge: {knowledge}\n"
            f"Specifically verify and correct: {flag_str}\n"
            f"Answer:"
        )
        answer = generate_text(prompt, model, tokenizer)

        # Word overlap consistency check (proxy for Loop 2 scoring)
        q_words = set(question.lower().split())
        a_words = set(answer.lower().split())
        k_words = set(knowledge.lower().split())

        consistency = len(a_words & k_words) / (len(k_words) + 1)
        if consistency > 0.1:  # some overlap with knowledge
            break

    return answer


def loop3_entailment(question, answer):
    """Loop 3: Check keyword coverage — does answer address the question?"""
    q_words = set(question.lower().split())
    a_words = set(answer.lower().split())

    # Filter stopwords
    stopwords = {'the','a','an','is','are','was','were','what','how','why',
                 'when','which','who','does','do','did','in','of','to','for',
                 'and','or','but','with','by','at','from','that','this'}
    q_content = q_words - stopwords

    if not q_content:
        return True

    coverage = len(q_content & a_words) / len(q_content)
    return coverage >= 0.8


print('Self-reflection loops defined.')

def generate_baseline_answer(question, model, tokenizer):
    """Stage 1: Direct answer generation with no correction."""
    prompt = f"Answer this medical question concisely and accurately.\nQuestion: {question}\nAnswer:"
    return generate_text(prompt, model, tokenizer)


def atsr_pipeline(question, model, tokenizer, detection_layers):
    """
    Full ATSR pipeline for one question.
    Returns: (baseline_answer, corrected_answer, triggered, scores)
    """
    # Stage 1: Initial generation
    baseline = generate_baseline_answer(question, model, tokenizer)

    # Stage 2: Activation scan (teacher forcing)
    outputs, inputs = teacher_forcing_pass(question, baseline, model, tokenizer)

    h_score = compute_hidden_score(outputs, detection_layers)
    a_score = compute_attention_score(outputs, detection_layers)
    e_score = compute_logit_entropy(outputs)

    scores = {'hidden': h_score, 'attention': a_score, 'entropy': e_score}

    # Decision gate
    if not is_hallucinated(h_score, a_score, e_score):
        # No hallucination detected — return baseline directly
        return baseline, baseline, False, scores

    # Stage 3: Token localization
    flagged_tokens = localize_hallucinated_tokens(outputs, tokenizer, inputs)

    # Stage 4: Self-reflection (up to 2 full restarts)
    best_answer = baseline
    best_f1     = 0.0

    for restart in range(2):
        knowledge = loop1_knowledge(question, flagged_tokens, model, tokenizer)
        corrected = loop2_answer(question, knowledge, flagged_tokens, model, tokenizer)

        if loop3_entailment(question, corrected):
            return baseline, corrected, True, scores

    # Return best found even if entailment not fully satisfied
    return baseline, corrected, True, scores


print('ATSR pipeline defined.')

import gc
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

# Models to test
MODELS = [
    {
        'name':             'Llama-3.1-8B',
        'hf_id':            'meta-llama/Meta-Llama-3.1-8B-Instruct',
        'quantize':         True,    # 4-bit to fit T4
        'detection_layers': DETECTION_LAYERS_8B
    },
]

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_use_double_quant=True
)


def load_model(model_cfg):
    print(f"Loading {model_cfg['name']}...")
    tokenizer = AutoTokenizer.from_pretrained(model_cfg['hf_id'])
    tokenizer.pad_token = tokenizer.eos_token

    if model_cfg['quantize']:
        model = AutoModelForCausalLM.from_pretrained(
            model_cfg['hf_id'],
            quantization_config=bnb_config,
            device_map='auto',
            attn_implementation='eager'   # ← fix
        )
    else:
        model = AutoModelForCausalLM.from_pretrained(
            model_cfg['hf_id'],
            torch_dtype=torch.float16,
            device_map='auto',
            attn_implementation='eager'   # ← fix
        )

    model.eval()
    print(f"  Loaded. VRAM: {torch.cuda.memory_allocated()/1e9:.2f} GB")
    return model, tokenizer

def unload_model(model):
    del model
    gc.collect()
    torch.cuda.empty_cache()
    print('  Model unloaded. VRAM cleared.')


print('Model runner ready.')

import time
import traceback
from tqdm import tqdm

all_results = {}

def run_model_benchmark(model_cfg, samples):
    model, tokenizer = load_model(model_cfg)
    detection_layers = model_cfg['detection_layers']
    results = []

    for i, sample in enumerate(tqdm(samples, desc=model_cfg['name'])):
        question     = sample['question']
        ground_truth = sample['long_answer']

        try:
            baseline, corrected, triggered, scores = atsr_pipeline(
                question, model, tokenizer, detection_layers
            )
            f1_before = compute_f1(baseline,  ground_truth)
            f1_after  = compute_f1(corrected, ground_truth)

            results.append({
                'question':     question,
                'ground_truth': ground_truth,
                'baseline':     baseline,
                'corrected':    corrected,
                'f1_before':    f1_before,
                'f1_after':     f1_after,
                'triggered':    triggered,
                'scores':       scores
            })

        except Exception as e:
            # ── Print FULL traceback so we can see the real error ──
            print(f'\n  ERROR on sample {i}:')
            print(f'  Question: {question[:80]}')
            traceback.print_exc()  # <-- this is the key addition
            results.append({
                'f1_before': 0.0, 'f1_after': 0.0,
                'triggered': False, 'error': str(e)
            })

        # ── Print first sample result so we know it's working ──
        if i == 0 and results and 'error' not in results[0]:
            print(f'\n  Sample 0 OK — F1 before: {results[0]["f1_before"]:.3f}, '
                  f'after: {results[0]["f1_after"]:.3f}, '
                  f'triggered: {results[0]["triggered"]}')

    unload_model(model)
    return results


for model_cfg in MODELS:
    print(f"\n{'='*60}")
    print(f"  Benchmarking: {model_cfg['name']}")
    print(f"{'='*60}")

    t0      = time.time()
    results = run_model_benchmark(model_cfg, samples)
    elapsed = time.time() - t0

    valid_results = [r for r in results if 'error' not in r]
    error_count   = len(results) - len(valid_results)

    print(f'\n  Completed: {len(valid_results)} ok, {error_count} errors')

    if not valid_results:
        print(f'  !! ALL SAMPLES FAILED for {model_cfg["name"]} — check errors above')
        continue  # skip aggregation, move to next model

    f1_before_list = [r['f1_before'] for r in valid_results]
    f1_after_list  = [r['f1_after']  for r in valid_results]
    trigger_rate   = sum(r['triggered'] for r in valid_results) / len(valid_results)

    avg_f1_before = np.mean(f1_before_list)
    avg_f1_after  = np.mean(f1_after_list)
    improvement   = avg_f1_after - avg_f1_before

    all_results[model_cfg['name']] = {
        'f1_before':    avg_f1_before,
        'f1_after':     avg_f1_after,
        'improvement':  improvement,
        'trigger_rate': trigger_rate,
        'per_sample':   results,
        'runtime_min':  elapsed / 60
    }

    print(f"    F1 Before ATSR : {avg_f1_before:.4f}")
    print(f"    F1 After  ATSR : {avg_f1_after:.4f}")
    print(f"    Improvement    : {improvement:+.4f}")
    print(f"    Trigger rate   : {trigger_rate:.1%}")
    print(f"    Runtime        : {elapsed/60:.1f} min")

print('\n✓ Done.')

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

# ── Data prep ──────────────────────────────────────────────────
model_names   = list(all_results.keys())
f1_before     = [all_results[m]['f1_before']    for m in model_names]
f1_after      = [all_results[m]['f1_after']     for m in model_names]
trigger_rates = [all_results[m]['trigger_rate'] for m in model_names]

x      = np.arange(len(model_names))
width  = 0.35

# ── Color scheme ───────────────────────────────────────────────
COLOR_BEFORE = '#E05C5C'   # red — hallucination before
COLOR_AFTER  = '#4CAF82'   # green — reduced hallucination after
COLOR_BG     = '#0F1117'
COLOR_TEXT   = '#E8E8E8'
COLOR_GRID   = '#2A2D35'

plt.rcParams.update({
    'font.family':       'monospace',
    'text.color':        COLOR_TEXT,
    'axes.labelcolor':   COLOR_TEXT,
    'xtick.color':       COLOR_TEXT,
    'ytick.color':       COLOR_TEXT,
    'figure.facecolor':  COLOR_BG,
    'axes.facecolor':    COLOR_BG,
    'axes.edgecolor':    COLOR_GRID,
    'grid.color':        COLOR_GRID,
})

fig, axes = plt.subplots(1, 3, figsize=(16, 6))
fig.suptitle('ATSR Hallucination Benchmark — PubMedQA',
             fontsize=14, fontweight='bold', color=COLOR_TEXT, y=1.02)

# ── Plot 1: F1 Before vs After (grouped bar) ───────────────────
ax1 = axes[0]
bars1 = ax1.bar(x - width/2, f1_before, width,
                label='Before ATSR', color=COLOR_BEFORE, alpha=0.9, zorder=3)
bars2 = ax1.bar(x + width/2, f1_after,  width,
                label='After ATSR',  color=COLOR_AFTER,  alpha=0.9, zorder=3)

ax1.set_xlabel('Model')
ax1.set_ylabel('F1 Score')
ax1.set_title('F1 Score: Before vs After ATSR')
ax1.set_xticks(x)
ax1.set_xticklabels(model_names, rotation=10)
ax1.set_ylim(0, 1.0)
ax1.grid(axis='y', alpha=0.4, zorder=0)
ax1.legend()

# Value labels on bars
for bar in bars1:
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
             f'{bar.get_height():.3f}', ha='center', va='bottom',
             fontsize=9, color=COLOR_TEXT)
for bar in bars2:
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
             f'{bar.get_height():.3f}', ha='center', va='bottom',
             fontsize=9, color=COLOR_TEXT)

# ── Plot 2: F1 Improvement ─────────────────────────────────────
ax2 = axes[1]
improvements = [all_results[m]['improvement'] for m in model_names]
colors_imp   = [COLOR_AFTER if v >= 0 else COLOR_BEFORE for v in improvements]

bars3 = ax2.bar(x, improvements, color=colors_imp, alpha=0.9, zorder=3)
ax2.axhline(y=0, color=COLOR_TEXT, linewidth=0.8, linestyle='--', alpha=0.5)
ax2.set_xlabel('Model')
ax2.set_ylabel('F1 Improvement (After − Before)')
ax2.set_title('F1 Improvement from ATSR')
ax2.set_xticks(x)
ax2.set_xticklabels(model_names, rotation=10)
ax2.grid(axis='y', alpha=0.4, zorder=0)

for bar, val in zip(bars3, improvements):
    offset = 0.002 if val >= 0 else -0.005
    ax2.text(bar.get_x() + bar.get_width()/2, val + offset,
             f'{val:+.3f}', ha='center', va='bottom' if val >= 0 else 'top',
             fontsize=10, color=COLOR_TEXT, fontweight='bold')

# ── Plot 3: Trigger Rate ───────────────────────────────────────
ax3 = axes[2]
COLOR_TRIGGER = '#5B9BD5'

bars4 = ax3.bar(x, [r * 100 for r in trigger_rates],
                color=COLOR_TRIGGER, alpha=0.9, zorder=3)
ax3.axhline(y=37.6, color='#FFB347', linewidth=1.2, linestyle='--',
            alpha=0.7, label='Paper baseline (37.6%)')
ax3.set_xlabel('Model')
ax3.set_ylabel('Trigger Rate (%)')
ax3.set_title('ATSR Trigger Rate\n(% queries triggering self-reflection)')
ax3.set_xticks(x)
ax3.set_xticklabels(model_names, rotation=10)
ax3.set_ylim(0, 100)
ax3.grid(axis='y', alpha=0.4, zorder=0)
ax3.legend(fontsize=8)

for bar, val in zip(bars4, trigger_rates):
    ax3.text(bar.get_x() + bar.get_width()/2, val * 100 + 1,
             f'{val:.1%}', ha='center', va='bottom',
             fontsize=10, color=COLOR_TEXT)

plt.tight_layout()
plt.savefig('atsr_benchmark_results.png', dpi=150, bbox_inches='tight',
            facecolor=COLOR_BG)
plt.show()
print('Plot saved as atsr_benchmark_results.png')

print('\n' + '='*65)
print('  ATSR BENCHMARK SUMMARY — PubMedQA')
print('='*65)
print(f'  {"Model":<18} {"F1 Before":>10} {"F1 After":>10} {"Δ F1":>8} {"Trigger%":>10}')
print('-'*65)

for model_name in model_names:
    r = all_results[model_name]
    arrow = '↑' if r['improvement'] > 0 else ('↓' if r['improvement'] < 0 else '=')
    print(f'  {model_name:<18} {r["f1_before"]:>10.4f} {r["f1_after"]:>10.4f} '
          f'{arrow}{abs(r["improvement"]):>6.4f} {r["trigger_rate"]:>9.1%}')

print('='*65)

# Interpretation
best_model = max(model_names, key=lambda m: all_results[m]['improvement'])
print(f'\n  Best improvement: {best_model} '
      f'(+{all_results[best_model]["improvement"]:.4f} F1)')
print(f'  Sample size: {SAMPLE_SIZE} PubMedQA questions')
print(f'  Metric: Token-level F1 vs ground truth long_answer')

# Change this to inspect any model
INSPECT_MODEL = model_names[0]

per_sample = all_results[INSPECT_MODEL]['per_sample']
valid      = [r for r in per_sample if 'error' not in r]

# Sort by improvement
valid_sorted = sorted(valid, key=lambda r: r['f1_after'] - r['f1_before'], reverse=True)

print(f'\nTop 3 improvements for {INSPECT_MODEL}:')
print('-'*60)
for r in valid_sorted[:3]:
    delta = r['f1_after'] - r['f1_before']
    print(f'  Q: {r["question"][:70]}...')
    print(f'  F1: {r["f1_before"]:.3f} → {r["f1_after"]:.3f}  (Δ {delta:+.3f})')
    print(f'  Triggered: {r["triggered"]}')
    print()

print(f'\nTop 3 regressions for {INSPECT_MODEL}:')
print('-'*60)
for r in valid_sorted[-3:]:
    delta = r['f1_after'] - r['f1_before']
    print(f'  Q: {r["question"][:70]}...')
    print(f'  F1: {r["f1_before"]:.3f} → {r["f1_after"]:.3f}  (Δ {delta:+.3f})')
    print(f'  Triggered: {r["triggered"]}')
    print()

import json

# Strip per-sample detail for clean save
summary = {
    model: {
        'f1_before':    all_results[model]['f1_before'],
        'f1_after':     all_results[model]['f1_after'],
        'improvement':  all_results[model]['improvement'],
        'trigger_rate': all_results[model]['trigger_rate'],
        'runtime_min':  all_results[model]['runtime_min'],
        'sample_size':  SAMPLE_SIZE
    }
    for model in model_names
}

with open('atsr_benchmark_summary.json', 'w') as f:
    json.dump(summary, f, indent=2)

print('Results saved to atsr_benchmark_summary.json')
print(json.dumps(summary, indent=2))

import matplotlib.pyplot as plt
import numpy as np

all_results = {
    'Llama-3.2-3B': {'f1_before': 0.2436, 'f1_after': 0.2011,
                     'improvement': -0.0425, 'trigger_rate': 1.0},
    'Mistral-7B':   {'f1_before': 0.2661, 'f1_after': 0.2624,
                     'improvement': -0.0037, 'trigger_rate': 1.0},
    'Llama-3.1-8B': {'f1_before': 0.2299, 'f1_after': 0.2170,
                     'improvement': -0.0129, 'trigger_rate': 1.0},
}
model_names   = list(all_results.keys())
f1_before     = [all_results[m]['f1_before']    for m in model_names]
f1_after      = [all_results[m]['f1_after']     for m in model_names]
improvements  = [all_results[m]['improvement']  for m in model_names]
trigger_rates = [all_results[m]['trigger_rate'] * 100 for m in model_names]

x     = np.arange(len(model_names))
width = 0.35

COLOR_BEFORE = '#E24B4A'
COLOR_AFTER  = '#1D9E75'
COLOR_DELTA  = ['#E24B4A' if v < 0 else '#1D9E75' for v in improvements]
COLOR_TRIGGER = '#378ADD'
COLOR_BG     = '#0F1117'
COLOR_TEXT   = '#E8E8E8'
COLOR_GRID   = '#2A2D35'

plt.rcParams.update({
    'font.family':      'monospace',
    'text.color':       COLOR_TEXT,
    'axes.labelcolor':  COLOR_TEXT,
    'xtick.color':      COLOR_TEXT,
    'ytick.color':      COLOR_TEXT,
    'figure.facecolor': COLOR_BG,
    'axes.facecolor':   COLOR_BG,
    'axes.edgecolor':   COLOR_GRID,
    'grid.color':       COLOR_GRID,
})

fig, axes = plt.subplots(1, 3, figsize=(16, 6))
fig.suptitle('ATSR Hallucination Benchmark — PubMedQA (50 samples)',
             fontsize=13, fontweight='bold', color=COLOR_TEXT, y=1.02)

# ── Plot 1: F1 Before vs After ─────────────────────────────────
ax1 = axes[0]
b1 = ax1.bar(x - width/2, f1_before, width, label='Before ATSR',
             color=COLOR_BEFORE, alpha=0.9, zorder=3)
b2 = ax1.bar(x + width/2, f1_after,  width, label='After ATSR',
             color=COLOR_AFTER,  alpha=0.9, zorder=3)

ax1.set_title('F1 Score: Before vs After ATSR', color=COLOR_TEXT)
ax1.set_ylabel('F1 Score')
ax1.set_xticks(x)
ax1.set_xticklabels(model_names, rotation=10, fontsize=9)
ax1.set_ylim(0.15, 0.30)
ax1.grid(axis='y', alpha=0.4, zorder=0)
ax1.legend(fontsize=9)

for bar in b1:
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001,
             f'{bar.get_height():.3f}', ha='center', va='bottom',
             fontsize=8, color=COLOR_TEXT)
for bar in b2:
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001,
             f'{bar.get_height():.3f}', ha='center', va='bottom',
             fontsize=8, color=COLOR_TEXT)

# ── Plot 2: F1 Improvement ─────────────────────────────────────
ax2 = axes[1]
b3 = ax2.bar(x, improvements, color=COLOR_DELTA, alpha=0.9, zorder=3)
ax2.axhline(y=0, color=COLOR_TEXT, linewidth=0.8, linestyle='--', alpha=0.4)
ax2.set_title('F1 Improvement (After − Before)', color=COLOR_TEXT)
ax2.set_ylabel('Δ F1')
ax2.set_xticks(x)
ax2.set_xticklabels(model_names, rotation=10, fontsize=9)
ax2.grid(axis='y', alpha=0.4, zorder=0)

for bar, val in zip(b3, improvements):
    offset = 0.0005 if val >= 0 else -0.002
    va     = 'bottom' if val >= 0 else 'top'
    ax2.text(bar.get_x() + bar.get_width()/2, val + offset,
             f'{val:+.4f}', ha='center', va=va,
             fontsize=9, fontweight='bold', color=COLOR_TEXT)

# ── Plot 3: Trigger Rate ───────────────────────────────────────
ax3 = axes[2]
b4 = ax3.bar(x, trigger_rates, color=COLOR_TRIGGER, alpha=0.9, zorder=3)
ax3.axhline(y=37.6, color='#EF9F27', linewidth=1.5, linestyle='--',
            alpha=0.8, label='Paper baseline (37.6%)')
ax3.set_title('ATSR Trigger Rate', color=COLOR_TEXT)
ax3.set_ylabel('Trigger Rate (%)')
ax3.set_xticks(x)
ax3.set_xticklabels(model_names, rotation=10, fontsize=9)
ax3.set_ylim(0, 120)
ax3.grid(axis='y', alpha=0.4, zorder=0)
ax3.legend(fontsize=8)

for bar, val in zip(b4, trigger_rates):
    ax3.text(bar.get_x() + bar.get_width()/2, val + 1,
             f'{val:.0f}%', ha='center', va='bottom',
             fontsize=9, color=COLOR_TEXT)

plt.tight_layout()
plt.savefig('atsr_final_results.png', dpi=150,
            bbox_inches='tight', facecolor=COLOR_BG)
plt.show()
print('Saved: atsr_final_results.png')